version: '3'


services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./app:/opt/app
      - ./docker/php/zz-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
  web:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./app:/opt/app
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
  mysql:
    image: mysql:latest
    volumes:
      - ./app:/opt/app
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8181:80
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui